import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { 
  NgbNavModule,
  NgbAlertModule,
  NgbModalModule,
  NgbToastModule,
  NgbRatingModule,
  NgbButtonsModule,
  NgbPopoverModule,
  NgbTooltipModule,
  NgbCarouselModule,
  NgbCollapseModule,
  NgbDropdownModule,
  NgbAccordionModule,
  NgbTypeaheadModule,
  NgbDatepickerModule,
  NgbPaginationModule,
  NgbTimepickerModule,
  NgbProgressbarModule, 
} from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  imports: [
    CommonModule, 
    NgbNavModule,
    NgbAlertModule,
    NgbModalModule,
    NgbToastModule,
    NgbRatingModule,
    NgbButtonsModule,
    NgbPopoverModule,
    NgbTooltipModule,
    NgbCarouselModule,
    NgbCollapseModule,
    NgbDropdownModule,
    NgbAccordionModule,
    NgbTypeaheadModule,
    NgbDatepickerModule,
    NgbPaginationModule,
    NgbTimepickerModule,
    NgbProgressbarModule, 
  ],
  exports: [  
    NgbNavModule,
    NgbAlertModule,
    NgbModalModule,
    NgbToastModule,
    NgbRatingModule,
    NgbButtonsModule,
    NgbPopoverModule,
    NgbTooltipModule,
    NgbCarouselModule,
    NgbCollapseModule,
    NgbDropdownModule,
    NgbAccordionModule,
    NgbTypeaheadModule,
    NgbDatepickerModule,
    NgbPaginationModule,
    NgbTimepickerModule,
    NgbProgressbarModule, 
  ],
})
export class BoostwachModule {
} 
